### ISSUE TITLE
Partial iLIDS dataset

### ISSUE THREAD

**Issue by dichen-cd** [JDAI-CV/Partial-Person-ReID#7]
Hello~ 

Looks like Partial iLIDS dataset you provided is not quite correct. There're only 119 images in the Gallery. I guess the correct amount should be 357?

**Comment by dichen-cd** [comment]
119 images in the Gallery set is correct. Sorry about the mistake.

**Comment by 22wei22** [comment]
Can you provide me the link for Partial iLIDS and Partial ReID datasets？

**Comment by huo123lijuan** [comment]
> 119 images in the Gallery set is correct. Sorry about the mistake.

why Partial iLIDS dataset is 119 images?
